### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by novski** [KizzyCode/fritznet-nodered#1]
I tried an installation from the Pallettemanager in NR and got an error:

```
cat /home/novski/.npm/_logs/2023-07-30T17_37_23_444Z-debug-0.log
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@8.19.4
2 info using node@v16.20.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 warn config production Use `--omit=dev` instead.
8 timing config:load:cli Completed in 7ms
9 timing config:load:env Completed in 0ms
10 timing config:load:file:/home/novski/.node-red/.npmrc Completed in 0ms
11 timing config:load:project Completed in 21ms
12 timing config:load:file:/home/novski/.npmrc Completed in 2ms
13 timing config:load:user Completed in 3ms
14 timing config:load:file:/usr/etc/npmrc Completed in 0ms
15 timing config:load:global Completed in 1ms
16 timing config:load:validate Completed in 0ms
17 timing config:load:credentials Completed in 3ms
18 timing config:load:setEnvs Completed in 3ms
19 timing config:load Completed in 49ms
20 timing npm:load:configload Completed in 50ms
21 timing npm:load:mkdirpcache Completed in 2ms
22 timing npm:load:mkdirplogs Completed in 1ms
23 verbose title npm install node-red-contrib-fritznet@0.2.3
24 verbose argv "install" "--no-audit" "--no-update-notifier" "--no-fund" "--save" "--save-prefix" "~" "--production" "--engine-strict" "node-red-contrib-fritznet@0.2.3"
25 timing npm:load:setTitle Completed in 5ms
26 timing config:load:flatten Completed in 8ms
27 timing npm:load:display Completed in 13ms
28 verbose logfile logs-max:10 dir:/home/novski/.npm/_logs
29 verbose logfile /home/novski/.npm/_logs/2023-07-30T17_37_23_444Z-debug-0.log
30 timing npm:load:logFile Completed in 15ms
31 timing npm:load:timers Completed in 0ms
32 timing npm:load:configScope Completed in 0ms
33 timing npm:load Completed in 90ms
34 timing arborist:ctor Completed in 2ms
35 silly logfile start cleaning logs, removing 1 files
36 silly logfile done cleaning log files
37 timing idealTree:init Completed in 454ms
38 timing idealTree:userRequests Completed in 8ms
39 silly idealTree buildDeps
40 silly fetch manifest node-red-contrib-fritznet@0.2.3
41 timing arborist:ctor Completed in 0ms
42 http fetch GET 200 https://registry.npmjs.org/node-red-contrib-fritznet 1103ms (cache miss)
43 silly placeDep ROOT node-red-contrib-fritznet@ OK for: node-red-project@0.0.1 want: 0.2.3
44 timing idealTree:#root Completed in 1123ms
45 timing idealTree:node_modules/node-red-contrib-fritznet Completed in 0ms
46 timing idealTree:buildDeps Completed in 1126ms
47 timing idealTree:fixDepFlags Completed in 8ms
48 timing idealTree Completed in 1600ms
49 timing command:install Completed in 1618ms
50 verbose stack TypeError: Cannot convert undefined or null to object
50 verbose stack     at Function.keys (<anonymous>)
50 verbose stack     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:213:22)
50 verbose stack     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
50 verbose stack     at async Arborist.[nodeFromEdge] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:19)
50 verbose stack     at async Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
50 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
50 verbose stack     at async Promise.all (index 1)
50 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
50 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:145:5)
50 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:78:5)
51 verbose cwd /home/novski/.node-red
52 verbose Linux 6.1.21-v8+
53 verbose node v16.20.1
54 verbose npm  v8.19.4
55 error Cannot convert undefined or null to object
56 verbose exit 1
57 timing npm Completed in 1963ms
58 verbose unfinished npm timer reify 1690738643781
59 verbose unfinished npm timer reify:loadTrees 1690738643791
60 verbose code 1
61 error A complete log of this run can be found in:
61 error     /home/novski/.npm/_logs/2023-07-30T17_37_23_444Z-debug-0.log
```
Can I help debug this further somehow?

**Comment by KizzyCode** [comment]
Hey, thank you for your report. How did you try to install the module? 

## Background
I've deleted this module from NPM, however it seems that the flow registry has maintained an orphaned index to the non-existing NPM package. The recommended way to install this module is via `npm install git+https://github.com/KizzyCode/fritznet-nodered.git`, however you can also install the packaged version via the palette UI if you want; see https://github.com/KizzyCode/fritznet-nodered/releases/tag/0.2.3 – hope this helps 😊
